name: Noop Implementation Macro CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality Check
    uses: ./.github/workflows/code-quality.yml
    permissions:
      contents: read

  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/run-tests.yml
    permissions:
      contents: read

  notify-completion:
    name: Notify Completion Status
    runs-on: ubuntu-latest
    needs: [code-quality, build-and-test]
    if: always() && github.event_name == 'pull_request' # PR時のみ実行 (always() で依存ジョブ失敗時も実行しステータスを報告)
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Determine Status Icons
        id: icons
        run: |
          echo "quality_icon=${{ needs.code-quality.result == 'success' && '✅' || '❌' }}" >> $GITHUB_OUTPUT
          echo "test_icon=${{ needs.build-and-test.result == 'success' && '✅' || '❌' }}" >> $GITHUB_OUTPUT
          # 全体的なステータスを決定
          if [[ "${{ needs.code-quality.result }}" == "success" && "${{ needs.build-and-test.result }}" == "success" ]]; then
            echo "overall_status=success" >> $GITHUB_OUTPUT
            echo "overall_icon=✅" >> $GITHUB_OUTPUT
            echo "message=All checks passed successfully!" >> $GITHUB_OUTPUT
          else
            echo "overall_status=failure" >> $GITHUB_OUTPUT
            echo "overall_icon=❌" >> $GITHUB_OUTPUT
            echo "message=One or more checks failed." >> $GITHUB_OUTPUT
          fi

      - name: Add Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `## CI/CD Pipeline Completed ${{ steps.icons.outputs.overall_icon }}
              
              ${{ steps.icons.outputs.message }}
              
              ### Status Summary:
              - Code Quality Check: ${{ steps.icons.outputs.quality_icon }}
              - Build and Test: ${{ steps.icons.outputs.test_icon }}
              `
            }); 