name: Run Tests

on:
  workflow_call:

jobs:
  test:
    name: Run Swift Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'

      - name: Run Tests
        run: swift test 